---
# Genera certificados auto-firmados por 61 días directamente en el directorio files/ del rol
# Requiere collections: community.crypto, kubernetes.core

- name: Generar certificados de ingress por 61 días en files/ del rol
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - vars.yml
  vars:
    files_dir: "{{ playbook_dir }}/certificado/files"
    validity_days: 61
  tasks:
    - name: Calcular clusters con token resuelto
      ansible.builtin.set_fact:
        clusters_ready: "{{ clusters | selectattr('token','defined') | rejectattr('token','search','{{') | list }}"
        clusters_skipped: "{{ clusters | selectattr('token','defined') | selectattr('token','search','{{') | map(attribute='name') | list }}"

    - name: Mostrar clusters omitidos por token no resuelto (si los hay)
      ansible.builtin.debug:
        msg: "Omitiendo clústeres por token no resuelto: {{ clusters_skipped | join(', ') }}"
      when: clusters_skipped | length > 0

    - name: Fallar si no hay clústeres con token resuelto
      ansible.builtin.fail:
        msg: "No hay clústeres con token resuelto. Define tus tokens (Ansible Vault) o comenta los clústeres sin token."
      when: clusters_ready | length == 0

    - name: Crear directorio files del rol
      ansible.builtin.file:
        path: "{{ files_dir }}"
        state: directory
        mode: "0750"

    - name: Obtener información del recurso ingresses.config/cluster - {{ item.name }}
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Ingress
        name: cluster
        host: "{{ item.api_url }}"
        api_key: "{{ item.token }}"
        validate_certs: false
      register: ingress_cfg
      loop: "{{ clusters_ready }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: false
      ignore_errors: true

    - name: Mostrar errores de consulta de dominio por clúster (si los hay)
      ansible.builtin.debug:
        msg: "{{ item.item.name }} => error: {{ item.msg | default(item.stderr | default(item.exception | default('unknown error'))) }}"
      when: item is failed
      loop: "{{ ingress_cfg.results | default([]) }}"
      loop_control:
        label: "{{ item.item.name | default('unknown') }}"

    - name: Fallar si algún clúster no devolvió el dominio
      ansible.builtin.fail:
        msg: "Fallo al obtener ingresses.config/cluster en uno o más clústeres. Revisa mensajes anteriores."
      when: (ingress_cfg.results | default([]) | selectattr('failed','defined') | selectattr('failed') | list | length) > 0

    - name: Preparar facts con dominio y SANs
      ansible.builtin.set_fact:
        cluster_domains: "{{ (cluster_domains | default({})) | combine({ item.item.name: item.resources[0].spec.domain }) }}"
        cluster_sans: "{{ (cluster_sans | default({})) | combine({ item.item.name: [ '*.apps.' + item.resources[0].spec.domain ] }) }}"
      loop: "{{ ingress_cfg.results | default([]) }}"
      loop_control:
        label: "{{ item.item.name }} => {{ item.resources[0].spec.domain | default('unknown') }}"
      when: item is succeeded and (item.resources | default([])) | length > 0

    - name: Generar clave privada para {{ item.name }} en files/ del rol
      community.crypto.openssl_privatekey:
        path: "{{ files_dir }}/{{ item.name }}-key.pem"
        size: 2048
        type: RSA
        mode: "0600"
      loop: "{{ clusters_ready }}"
      loop_control:
        label: "{{ item.name }}"
      when: cluster_domains is defined and (cluster_domains[item.name] | default('')) != ''

    - name: Generar CSR para {{ item.name }} en files/ del rol
      community.crypto.openssl_csr:
        path: "{{ files_dir }}/{{ item.name }}.csr"
        privatekey_path: "{{ files_dir }}/{{ item.name }}-key.pem"
        common_name: "*.apps.{{ cluster_domains[item.name] }}"
        subject_alt_name: "{{ cluster_sans[item.name] | map('regex_replace', '^(.*)$', 'DNS:\\1') | list }}"
      loop: "{{ clusters_ready }}"
      loop_control:
        label: "{{ item.name }}"
      when: cluster_domains is defined and (cluster_domains[item.name] | default('')) != ''

    - name: Generar certificado auto-firmado por {{ validity_days }} días para {{ item.name }} en files/ del rol
      community.crypto.x509_certificate:
        path: "{{ files_dir }}/{{ item.name }}-cert.pem"
        privatekey_path: "{{ files_dir }}/{{ item.name }}-key.pem"
        csr_path: "{{ files_dir }}/{{ item.name }}.csr"
        provider: selfsigned
        selfsigned_not_after: "+{{ validity_days }}d"
        mode: "0644"
      loop: "{{ clusters_ready }}"
      loop_control:
        label: "{{ item.name }}"
      when: cluster_domains is defined and (cluster_domains[item.name] | default('')) != ''

    - name: Mostrar rutas generadas en files/ del rol
      ansible.builtin.debug:
        msg: "{{ item.name }} => cert: {{ files_dir }}/{{ item.name }}-cert.pem, key: {{ files_dir }}/{{ item.name }}-key.pem"
      loop: "{{ clusters_ready }}"
      loop_control:
        label: "{{ item.name }}"
      when: cluster_domains is defined and (cluster_domains[item.name] | default('')) != ''

    - name: Mostrar resumen de archivos generados en files/ del rol
      ansible.builtin.debug:
        msg: |
          Certificados de {{ validity_days }} días generados en files/ del rol:
          {% for cluster in clusters_ready %}
          - {{ cluster.name }}: {{ files_dir }}/{{ cluster.name }}-cert.pem
          {% endfor %}