---
# Archivo de requirements para el rol de certificados
# Instala las colecciones necesarias para el funcionamiento del rol

collections:
  - name: community.crypto
    version: ">=1.0.0"
  - name: kubernetes.core
    version: ">=2.0.0"

# Si quieres instalar el rol desde un repositorio
# roles:
#   - name: tuusuario.certificado
#     src: https://github.com/tuusuario/ansible-role-certificado
#     version: main 